### ISSUE TITLE
Include the Table of Contents

### ISSUE THREAD

**Issue by wyatt-wong** [tomaz/zx-next-dev-guide#16]
Suggest to include the "Table of Contents" before the Contents page.

**Comment by tomaz** [comment]
Thanks for suggestion! I'm not sure I understand though - TOC is before content already, isn't it? See screenshot for latest format showing page spread (as if book is open with both pages, odd and even visible):

1. Title page (even page - blank cover sheet comes to the left, not shown on screenshot)

2. Copyright info on the back side of the title page + Acknowlegements on the right side

3. TOC

4. Start of content, first chapter: introduction, followed by Z80 chapter

I show first 2 chapters in here because introduction no longer has chapter TOC (there's no point really + it takes substantial space from more important information - "Companion Source Guide") and to show the new format for chapter TOC - it only includes sections now, not subsections as it did before. This was necessary as Next chapter grew quite a bit and its TOC became too large to fit on single page spread...

Let me know if I misunderstood something!

![preview](https://user-images.githubusercontent.com/77294/136744476-e54886a3-06a6-44d4-a263-8549f84b4a63.jpg)

**Comment by tomaz** [comment]
Is this what you had in mind?

It created chapter TOC for introduction for some reason, seen on screenshot, I'll remove it.

I'm not biased regarding this when it comes to downloadable PDF, I can leave it like this. It's trivial to change, if many readers will be against. But again, printed book will have previous representation with just sections included.

![toc2](https://user-images.githubusercontent.com/77294/136770156-dd577995-e982-4e55-8585-0d8aa91213be.jpg)

**Comment by wyatt-wong** [comment]
> Is this what you had in mind?
> 
> It created chapter TOC for introduction for some reason, seen on screenshot, I'll remove it.
> 
> I'm not biased regarding this when it comes to downloadable PDF, I can leave it like this. It's trivial to change, if many readers will be against. But again, printed book will have previous representation with just sections included.
> 
> ![toc2](https://user-images.githubusercontent.com/77294/136770156-dd577995-e982-4e55-8585-0d8aa91213be.jpg)

I think it looks nice. On the other hand, I noticed the previous thumbs package for LaTeX is already included in the MiKTeX TeX distribution. The MiKTeX package is mentioned in your "Editing" section in the readme.md

https://ctan.org/pkg/thumbs?lang=en
